Hw2: HashTable tests and Matrix together
vasyoid/java2017 pull request #2
Opened 2017-09-27 18:35 UTC by vasilyPML30

2017-10-03 08:02 UTC, yurii-litvinov requested changes
Папку .gradle выкладывать не надо, это локальный кеш системы сборки. Ещё, в принципе, можно не выкладывать папку .idea, IDEA может пересоздать проект по gradle.build. Но это дело вкуса, потому что если хочется настройки, общие для команды разработчиков, .idea выкладывать всё-таки надо.

Итого обе задачи про хеш-таблицу зачтены, а задачу про матрицы надо поправить.

2017-10-03 08:02 UTC, yurii-litvinov commented on HashTable/src/net/netau/vasyoid/HashTable.java
> +    private int size, capacity;
Более канонично каждое поле объявлять отдельно

2017-10-03 08:02 UTC, yurii-litvinov commented on HashTable/src/net/netau/vasyoid/LinkedList.java
> +    private class ListNode {
Он мог бы быть static, раз он не использует ссылку на объект объемлющего класса

2017-10-03 08:02 UTC, yurii-litvinov commented on HashTable/src/net/netau/vasyoid/LinkedList.java
> +            this.previous = this.next = this;
На мой вкус лучше это как два отдельных присваивания записать

2017-10-03 08:02 UTC, yurii-litvinov commented on HashTable/src/net/netau/vasyoid/LinkedList.java
> +
Между комментарием и классом иногда делается пустая строка, иногда нет. Но в рамках одного проекта лучше выбрать что-то одно и придерживаться этого всюду

2017-10-03 08:02 UTC, yurii-litvinov commented on Matrix/src/main/java/net/netau/vasyoid/Main.java
> +                System.out.print(matrix[row * size + col] + " ");
Ох. Мне кажется, проще было представлять матрицу как двумерный массив. Тогда он знал бы свой размер, и size передавать было бы не нужно.

2017-10-03 08:02 UTC, yurii-litvinov commented on Matrix/src/main/java/net/netau/vasyoid/Matrix.java
> +            throw new IllegalArgumentException("matrix size and number of elements do not match");
Лучше сначала проверку, а потом вызов конструктора

2017-10-03 08:02 UTC, yurii-litvinov commented on Matrix/src/test/java/net/netau/vasyoid/MatrixTest.java
> +import static org.junit.jupiter.api.Assertions.*;
А в build.gradle указывается зависимость только от junit 4.12 (jupiter.api --- это либа из JUnit 5), так что из консоли не компилится

2017-10-09 19:27 UTC, vasilyPML30 commented on Matrix/src/main/java/net/netau/vasyoid/Matrix.java
> +            throw new IllegalArgumentException("matrix size and number of elements do not match");
Но разве вызов другого конструктора не должен идти первой строчкой тела конструктора?

2017-10-21 18:21 UTC, yurii-litvinov approved these changes
Ага, всё ок

2017-10-21 18:21 UTC, yurii-litvinov commented on Matrix/src/main/java/net/netau/vasyoid/Matrix.java
> +            throw new IllegalArgumentException("matrix size and number of elements do not match");
Да, это я не по делу :) Можно было бы не вызывать конструктор, а сделать отдельный метод, который собственно инициализирует матрицу и вызывать его из обоих конструкторов, но это уже излишества

2017-10-21 18:21 UTC, yurii-litvinov commented on Matrix/src/test/java/net/netau/vasyoid/MatrixTest.java
> +        } catch(IllegalArgumentException e) {
Надо пробел перед "("

2017-11-07 14:11 UTC, merged